services:
  - type: web
    name: medissaclinic
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        sync: false
